create table if not exists public.trade_journal (
  id bigint generated by default as identity primary key,
  event_type text not null,
  symbol text not null,
  occurred_at timestamptz not null default now(),
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists trade_journal_symbol_occurred_at_idx
  on public.trade_journal (symbol, occurred_at desc);

create index if not exists trade_journal_event_type_occurred_at_idx
  on public.trade_journal (event_type, occurred_at desc);

alter table public.trade_journal enable row level security;

-- No anonymous/client insert policy is created here. The bot is expected to write
-- through a trusted server-side environment using the Supabase service-role key.
