import fs from 'node:fs';
const url='https://query1.finance.yahoo.com/v8/finance/chart/CSU.TO?range=2y&interval=1d&events=div%2Csplits';
const r=await fetch(url,{headers:{'User-Agent':'Mozilla/5.0 RUNLU-CSU-Research/1.3'}});if(!r.ok)throw new Error(`HTTP ${r.status}`);const d=await r.json(),x=d?.chart?.result?.[0],q=x?.indicators?.quote?.[0];if(!x?.timestamp||!q)throw new Error('No CSU data');
const candles=x.timestamp.map((t,i)=>({date:new Date(t*1000).toISOString().slice(0,10),open:+q.open[i],high:+q.high[i],low:+q.low[i],close:+q.close[i],volume:+(q.volume[i]||0)})).filter(c=>[c.open,c.high,c.low,c.close].every(Number.isFinite));
const avg=a=>a.length?a.reduce((s,v)=>s+v,0)/a.length:null, closes=candles.map(c=>c.close), sm=n=>closes.length>=n?avg(closes.slice(-n)):null;
function ema(v,p){if(v.length<p)return[];let z=avg(v.slice(0,p)),o=[z],k=2/(p+1);for(let i=p;i<v.length;i++){z=v[i]*k+z*(1-k);o.push(z)}return o}
function rsi(v,p=14){if(v.length<=p)return null;let g=0,l=0;for(let i=1;i<=p;i++){let z=v[i]-v[i-1];z>=0?g+=z:l-=z}let ag=g/p,al=l/p;for(let i=p+1;i<v.length;i++){let z=v[i]-v[i-1];ag=(ag*(p-1)+Math.max(z,0))/p;al=(al*(p-1)+Math.max(-z,0))/p}return al===0?100:100-100/(1+ag/al)}
const e12=ema(closes,12),e26=ema(closes,26),off=e12.length-e26.length,ms=e26.map((v,i)=>e12[i+off]-v),sg=ema(ms,9),recent=candles.slice(-20),price=closes.at(-1),ind={price,sma20:sm(20),sma50:sm(50),sma100:sm(100),sma200:sm(200),rsi14:rsi(closes),macd:ms.at(-1),macdSignal:sg.at(-1),support20:Math.min(...recent.map(c=>c.low)),resistance20:Math.max(...recent.map(c=>c.high))};
let score=0,reasons=[];if(ind.sma20){price>ind.sma20?(score++,reasons.push('Price is above SMA20')):(score--,reasons.push('Price is below SMA20'))}if(ind.sma20&&ind.sma50){ind.sma20>ind.sma50?(score++,reasons.push('SMA20 is above SMA50')):(score--,reasons.push('SMA20 is below SMA50'))}if(ind.sma50&&ind.sma200){ind.sma50>ind.sma200?(score++,reasons.push('Long-term trend is constructive')):(score--,reasons.push('Long-term trend remains weak'))}if(ind.rsi14<35){score++;reasons.push('RSI is near an oversold area')}else if(ind.rsi14>70){score--;reasons.push('RSI is elevated / overbought')}else reasons.push('RSI is neutral');if(ind.macd>ind.macdSignal){score++;reasons.push('MACD is above signal')}else{score--;reasons.push('MACD is below signal')}if(price<=ind.support20*1.03){score++;reasons.push('Price is close to 20-day support')}
const stance=score>=3?'BUY ZONE':score>=1?'WATCH':score>=-1?'HOLD':score>=-3?'CAUTION':'REDUCE',confidence=`${Math.min(90,50+Math.abs(score)*10)}%`;
fs.mkdirSync('public',{recursive:true});fs.writeFileSync('public/data.json',JSON.stringify({symbol:'CSU.TO',source:'Delayed/historical public chart feed',updatedAt:new Date().toISOString(),asOf:candles.at(-1)?.date,indicators:ind,analysis:{stance,confidence,reasons},candles},null,2));