type Candle={datetime:string;open:number;high:number;low:number;close:number;volume:number};
type IndicatorResult={price:number;changePct:number|null;sma20:number|null;sma50:number|null;sma100:number|null;sma200:number|null;rsi14:number|null;macd:number|null;macdSignal:number|null;atr14:number|null;volumeRatio:number|null;support20:number|null;resistance20:number|null};
const json=(data:unknown,status=200)=>new Response(JSON.stringify(data,null,2),{status,headers:{"content-type":"application/json; charset=utf-8","cache-control":"public, max-age=900","access-control-allow-origin":"*"}});
const avg=(xs:number[])=>xs.length?xs.reduce((a,b)=>a+b,0)/xs.length:null;
function ema(v:number[],p:number){if(v.length<p)return[];const k=2/(p+1),o:number[]=[];let x=v.slice(0,p).reduce((a,b)=>a+b,0)/p;o.push(x);for(let i=p;i<v.length;i++){x=v[i]*k+x*(1-k);o.push(x)}return o}
function rsi(v:number[],p=14){if(v.length<=p)return null;let g=0,l=0;for(let i=1;i<=p;i++){const d=v[i]-v[i-1];d>=0?g+=d:l-=d}let ag=g/p,al=l/p;for(let i=p+1;i<v.length;i++){const d=v[i]-v[i-1];ag=(ag*(p-1)+Math.max(d,0))/p;al=(al*(p-1)+Math.max(-d,0))/p}return al===0?100:100-100/(1+ag/al)}
function atr(c:Candle[],p=14){if(c.length<=p)return null;const t:number[]=[];for(let i=1;i<c.length;i++)t.push(Math.max(c[i].high-c[i].low,Math.abs(c[i].high-c[i-1].close),Math.abs(c[i].low-c[i-1].close)));let a=t.slice(0,p).reduce((x,y)=>x+y,0)/p;for(let i=p;i<t.length;i++)a=(a*(p-1)+t[i])/p;return a}
function indicators(c:Candle[]):IndicatorResult{const z=c.map(x=>x.close),vol=c.map(x=>x.volume).filter(Number.isFinite),price=z.at(-1)!,prev=z.at(-2)??null,e12=ema(z,12),e26=ema(z,26),off=e12.length-e26.length,m=e26.map((x,i)=>e12[i+off]-x),sig=ema(m,9),r20=c.slice(-20),av=avg(vol.slice(-20));const sm=(n:number)=>z.length>=n?avg(z.slice(-n)):null;return{price,changePct:prev?((price/prev)-1)*100:null,sma20:sm(20),sma50:sm(50),sma100:sm(100),sma200:sm(200),rsi14:rsi(z),macd:m.at(-1)??null,macdSignal:sig.at(-1)??null,atr14:atr(c),volumeRatio:av&&vol.at(-1)?vol.at(-1)!/av:null,support20:r20.length?Math.min(...r20.map(x=>x.low)):null,resistance20:r20.length?Math.max(...r20.map(x=>x.high)):null}}
function analyze(i:IndicatorResult){let s=0;const reasons:string[]=[];if(i.sma20!=null){i.price>i.sma20?(s++,reasons.push("Price is above SMA20")):(s--,reasons.push("Price is below SMA20"))}if(i.sma20!=null&&i.sma50!=null){i.sma20>i.sma50?(s++,reasons.push("SMA20 is above SMA50")):(s--,reasons.push("SMA20 is below SMA50"))}if(i.sma50!=null&&i.sma200!=null){i.sma50>i.sma200?(s++,reasons.push("Long-term trend is constructive")):(s--,reasons.push("Long-term trend remains weak"))}if(i.rsi14!=null){if(i.rsi14<35){s++;reasons.push("RSI is near an oversold area")}else if(i.rsi14>70){s--;reasons.push("RSI is elevated / overbought")}else reasons.push("RSI is in a neutral range")}if(i.macd!=null&&i.macdSignal!=null){i.macd>i.macdSignal?(s++,reasons.push("MACD is above signal")):(s--,reasons.push("MACD is below signal"))}const nearSupport=i.support20&&i.price<=i.support20*1.03;if(nearSupport){s++;reasons.push("Price is close to 20-day support")}const stance=s>=3?"BUY ZONE":s>=1?"WATCH":s>=-1?"HOLD":s>=-3?"CAUTION":"REDUCE";const confidence=Math.min(90,50+Math.abs(s)*10);return{stance,score:s,confidence:`${confidence}%`,reasons,disclaimer:"Research signal only; verify current brokerage data before any decision."}}
async function yahooDaily():Promise<Candle[]>{const u="https://query1.finance.yahoo.com/v8/finance/chart/CSU.TO?range=2y&interval=1d&events=div%2Csplits";const r=await fetch(u,{headers:{"user-agent":"Mozilla/5.0 RUNLU-CSU-Research/1.3"}});if(!r.ok)throw new Error(`Daily source HTTP ${r.status}`);const d:any=await r.json(),x=d?.chart?.result?.[0],q=x?.indicators?.quote?.[0];if(!x?.timestamp||!q)throw new Error("Daily source unavailable");return x.timestamp.map((t:number,i:number)=>({datetime:new Date(t*1000).toISOString().slice(0,10),open:+q.open[i],high:+q.high[i],low:+q.low[i],close:+q.close[i],volume:+(q.volume[i]||0)})).filter((c:Candle)=>[c.open,c.high,c.low,c.close].every(Number.isFinite))}
async function twelve(env:Env,interval:string):Promise<Candle[]>{if(!env.TWELVE_DATA_API_KEY)throw new Error("Intraday data source not configured");const u=new URL("https://api.twelvedata.com/time_series");u.searchParams.set("symbol","CSU:TSX");u.searchParams.set("interval",interval);u.searchParams.set("outputsize","300");const r=await fetch(u,{headers:{Authorization:`apikey ${env.TWELVE_DATA_API_KEY}`}});const d:any=await r.json();if(!d.values)throw new Error(d.message||"Intraday data unavailable");return d.values.slice().reverse().map((v:any)=>({datetime:v.datetime,open:+v.open,high:+v.high,low:+v.low,close:+v.close,volume:+(v.volume||0)})).filter((c:Candle)=>[c.open,c.high,c.low,c.close].every(Number.isFinite))}
export default{async fetch(request:Request,env:Env):Promise<Response>{const u=new URL(request.url);try{if(u.pathname==="/api/health")return json({ok:true,mode:"zero-cost daily first",symbol:"CSU.TO"});if(u.pathname==="/api/csu"){const interval=u.searchParams.get("interval")||"1day";let candles:Candle[],source:string;if(interval==="1day"){candles=await yahooDaily();source="Yahoo Finance chart (unofficial, delayed/historical)"}else if(interval==="1h"){candles=await twelve(env,"1h");source="Twelve Data intraday"}else return json({error:"2H will be enabled by aggregating 1H once a free intraday feed is available"},400);const ind=indicators(candles);return json({symbol:"CSU.TO",interval,source,asOf:candles.at(-1)?.datetime,indicators:ind,analysis:analyze(ind),candles:candles.slice(-520)})}return env.ASSETS.fetch(request)}catch(e){return json({error:"Unable to load CSU market data",detail:String(e)},502)}}};